sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0f4ea054945b_key -iv $encrypted_0f4ea054945b_iv -in articulate-case-252212-133773e1aa2c.json.enc -out articulate-case-252212-133773e1aa2c.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file articulate-case-252212-133773e1aa2c.json
  - gcloud config set project articulate-case-252212
  - gcloud config set compute/zone us-central1-a	
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ursash/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true ursash/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master